#
# https://www.metabase.com/docs/latest/installation-and-operation/running-metabase-on-docker
#

services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
    # only bind locally
    ports:
      - 127.0.0.1:3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_HOST: sql
      MB_DB_PORT: 5432
      MB_DB_USER: openthc_meta
      MB_DB_PASS: openthc_meta
      MB_DB_DBNAME: openthc_meta
    # healthcheck:
    #   test: curl --fail -I http://localhost:3000/api/health || exit 1
    #   interval: 15s
    #   timeout: 5s
    #   retries: 5
  # postgres:
  #   image: postgres:latest
  #   container_name: postgres
  #   hostname: postgres
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_DB: postgres
  #     POSTGRES_PASSWORD: postgres
